version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # conexão das apps
      - "15672:15672" # painel web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  migrator:
    build: ./OutboxPattern/OutboxPatternDbInitializer   # 👈 pasta da sua console app
    container_name: my_migrator
    depends_on:
      - postgres
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
    restart: "no"   # roda só uma vez e para

volumes:
  postgres_data:
